services:
  - type: web
    name: krmu-green
    env: node
    buildCommand: npm install --prefix server
    startCommand: npm start --prefix server
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: OTP_SECRET
        generateValue: true
